name: xsnow-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - jupyter
  - notebook
  - ipykernel
  # Scientific computing stack
  # Note: NumPy 2.x requires compatible packages (pyarrow>=14.0, numexpr>=2.9)
  # For NumPy 1.x compatibility, use: numpy>=1.20.0,<2.0.0
  - numpy>=1.20.0
  - pandas>=1.3.0
  - xarray>=2022.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - dask>=2022.0.0
  - netcdf4>=1.6.0
  - pyarrow>=14.0  # NumPy 2.x compatible
  - numexpr>=2.9   # NumPy 2.x compatible
  - pip:
    # Note: xsnow must be installed from git after creating the environment:
    #   pip install git+https://gitlab.com/avacollabra/postprocessing/xsnow
    # See README.md for complete installation instructions.

