name: xsnow-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - jupyter
  - notebook
  - ipykernel
  - numpy>=1.20.0
  - pandas>=1.3.0
  - xarray>=2022.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - dask>=2022.0.0
  - netcdf4>=1.6.0
  - pytest>=7.4
  - nbclient>=0.9
  - nbformat>=5.9
  - pre-commit>=3.6
  - black>=24.3
  - ruff>=0.2
  - nbstripout>=0.6
  - pip:
    # Note: xsnow must be installed from git after creating the environment:
    #   pip install git+https://gitlab.com/avacollabra/postprocessing/xsnow
    # See README.md for complete installation instructions.

